name: shope
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  card_swiper: ^2.0.4
  flutter_staggered_grid_view: ^0.6.2
  rubber: ^1.0.1
  pin_code_text_field: ^1.8.0
  http: ^0.13.4
  flutter_rating_bar: ^4.0.0
  intl: ^0.18.0
  numberpicker: ^2.1.1
  flutter_svg: ^2.0.2
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0
  build_runner: ^2.0.4
  json_serializable: ^6.6.1
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/shopeLogo.png"


flutter:

  uses-material-design: true

  assets:
  - assets/
  - assets/icons/

  fonts:
  - family: Montserrat
    fonts:
    - asset: fonts/Montserrat-Regular.ttf
  - family: NunitoSans
    fonts:
    - asset: fonts/NunitoSans-Regular.ttf
